version: '1'
services:
  redis:
    image: redis:latest
    container_name: redis_test
    ports:
      - '6389:6379'
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5